# GitHub for Developers Training Manual

Welcome to the first edition of the GitHub for Developers Training Manual.

You can find this book online at: ??

This project uses the Asciidoc format for the text of the manual.
We are also hoping to use O'Reilly's https://atlas.oreilly.com[Atlas platform] for generating continuous builds of the book.

== How To Generate the Manual

There are two ways to generate e-book content from this source code.

The easiest way is simply to let us do it.
A robot is standing by to look for new work on the main branch and automatically build it for everyone.

You can find the current builds on ?? and more information about the builds available at ??.

The other way to generate e-book files is to do so manually with Asciidoctor.
If you run the following you _may_ actually get HTML, Epub, Mobi and PDF output files:

----
$ bundle install
$ bundle exec rake book:build
Converting to HTML...
 -- HTML output at gh-for-devs-manual.html
Converting to EPub...
 -- Epub output at gh-for-devs-manual.epub
Converting to Mobi (kf8)...
 -- Mobi output at gh-for-devs-manual.mobi
Converting to PDF...
 -- PDF  output at gh-for-devs-manual.pdf
----

This uses the `asciidoctor`, `asciidoctor-pdf` and `asciidoctor-epub` projects.
