#!/usr/bin/env bash
#
# Install dependencies for the training manual and scripts

determine_package_manager() {
  # If script is running on macOS
  if [[ $OSTYPE == darwin* ]]; then
    # If Homebrew is not installed
    if ! type brew &>/dev/null; then
      echo "Installing Homebrew..."
      /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    fi
    package_manager="Homebrew"
  elif type apt &>/dev/null; then
    package_manager="APT"
  else
    package_manager="Unknown"
  fi
}

# NPM install
npm i docsify-cli -g

determine_package_manager

# Load the error code
ERROR_CODE=$?

# Check the shell for errors
if [ $ERROR_CODE -eq 0 ]; then
  # Success
  echo "Bootstrap successful"
else
  # Failure
  echo "ERROR! Failed to run bootstrap!"
  exit 1
fi
