#!/usr/bin/env bash
#
# Install dependencies for the training manual and scripts

# NPM install
npm i docsify-cli -g

# Load the error code
ERROR_CODE=$?

# Check the shell for errors
if [ $ERROR_CODE -eq 0 ]; then
  # Success
  echo "Bootstrap successful"
else
  # Failure
  echo "ERROR! Failed to run bootstrap!"
  exit 1
fi
