#!/bin/bash

# script/build: build all books and PDFs
# this can be used locally instead of running script/cibuild [BOOKNAME] to build all books

script/cibuild fullcicdtravis
script/cibuild fullcicdcircle
script/cibuild GH4D
script/cibuild GH4M
script/cibuild GH4DJA
