#!/bin/bash

# script/server: produce jekyll site of the manual

set -e

cd "$(dirname "$0")/.."

# use local gitbook
gitbook="./node_modules/.bin/gitbook"

# create new standard ${1} manual
[ -f "book/SUMMARY_${1}.md" ] && mv "book/SUMMARY_${1}.md" "book/SUMMARY.md"

sleep 1 # wait a little

echo "==> Building book ${1}..."
${gitbook} build >/dev/null 2>&1

echo "==> Generating PDF ${1}..."
${gitbook} pdf . ${1}.pdf >/dev/null 2>&1

sleep 1 # wait a little

[ -d "_book/" ] && mv "_book/" "${1}/"
[ -f "book/SUMMARY.md" ] && mv "book/SUMMARY.md" "book/SUMMARY_${1}.md"

echo -e "Done with ${1}.\n"
exit 0;
