#!/bin/bash

# script/server: produce jekyll site of the manual

set -e

cd "$(dirname "$0")/.."

# use local gitbook
gitbook="./node_modules/.bin/gitbook"

# create new standard ${1} manual
mv book/SUMMARY_GH4D.md book/SUMMARY.md

echo "==> Building book GH4D..."
${gitbook} build >/dev/null 2>&1

echo "==> Generating PDF GH4D..."
${gitbook} pdf . GH4D.pdf >/dev/null 2>&1

mv _book/ GH4D/
mv book/SUMMARY.md book/SUMMARY_GH4D.md

## Create new full CICD course for Travis
mv book/SUMMARY_CICD_FULLGH4D_TRAVIS.md book/SUMMARY.md

echo "==> Building book fullCICDTravis"
${gitbook} build

echo "==> Generating PDF fullCICDTravis"
${gitbook} pdf . fullCICDTravis.pdf

mv _book/ fullcicdtravis/

mv book/SUMMARY.md book/SUMMARY_CICD_FULLGH4D_TRAVIS.md

# create new full CICD course for Circle
mv book/SUMMARY_CICD_FULLGH4D_CIRCLE.md book/SUMMARY.md

echo "==> Building book fullCICDCircle"
${gitbook} build

echo "==> Generating PDF fullCICDCircle"
${gitbook} pdf . fullCICDCircle.pdf

mv _book/ fullcicdcircle/

mv book/SUMMARY.md book/SUMMARY_CICD_FULLGH4D_Circle.md

# create new GitHub for Managers manual
mv book/SUMMARY_GH4M.md book/SUMMARY.md

echo "==> Building book GH4M"
${gitbook} build

echo "==> Generating PDF GH4M"
${gitbook} pdf . GH4M.pdf

mv _book/ GH4M/

mv book/SUMMARY.md book/SUMMARY_GH4M.md
