#!/usr/bin/env bash
#
# Class Setup

#################################################################
# NOTE: You must have a personal access token (PAT)             #
# saved to your environment variables to use this script.       #
# We recommend a dedicated service account (e.g. githubteacher) #
#################################################################

# shellcheck source=script/ask
source ./ask

# GLOBALS
COLLAB_REPO=$1

function ContainsElement() {
  local e
  for e in "${@:2}"; do [[ "$e" == "$1" ]] && return 1; done
  return 0
}

function GetNames() {
  #grab template repo
  echo "Trying to clone a template repo from $ROOT_URL."

  # Check if github.com
  if [ "$ROOT_URL" = "github.com" ]; then
    # Clone the repo
    git clone --bare "https://github.com/githubtraining/polygons" conflict-template >>log.out 2>&1

    # Load the error code
    ERROR_CODE=$?

    # Check the shell for errors
    if [ $ERROR_CODE -ne 0 ]; then
      echo "ERROR! Failed to clone!"
      exit 1
    fi
  else
    # Clone the repo
    git clone --bare "https://$TOKEN_OWNER:$TEACHER_PAT@$ROOT_URL/$CLASS_ORG/polygons" conflict-template >>log.out 2>&1

    # Load the error code
    ERROR_CODE=$?

    # Check the shell for errors
    if [ $ERROR_CODE -ne 0 ]; then
      echo "!!! Couldn't clone template repo at all. Please grab a copy from https://github.com/githubtraining/polygons and upload it to your GHE instance."
      exit 1
    fi
  fi

  # Push the file
  pushd conflict-template || return

  # Get the collabs
  IFS=" " read -ra COLLABS <<<"$(
    curl -s -u "$TOKEN_OWNER:$TEACHER_PAT" -X GET "https://$INSTANCE_URL/repos/$CLASS_ORG/$COLLAB_REPO/collaborators?affiliation=direct&per_page=100" | jq -r 'map(.login) | unique | @sh' | tr -d \'
  )" >>log.out 2>&1

  # Create conflict repos based on COLLABS in the inital class repo
  for USER_NAME in "${COLLABS[@]}"; do
    REPO_STATUS=$(curl -s -i -u "$TOKEN_OWNER:$TEACHER_PAT" -X GET "https://$INSTANCE_URL/repos/$CLASS_ORG/conflict-practice-$USER_NAME" | grep "^Status:") >>log.out 2>&1
    echo "REPO_STATUS for $USER_NAME is $REPO_STATUS"
    if
      echo "$REPO_STATUS" | grep -iq "404"
    then
      CreateRepo "$USER_NAME"
    else
      # Check before cleaning up and recreating any duplicate repos
      if ask "A conflict-practice repo already exists for $USER_NAME. Is OK to delete and recreate?" N; then
        echo "Deleting and recreating $CLASS_ORG/conflict-practice-$USER_NAME repo..."
        curl -i -u "$TOKEN_OWNER:$TEACHER_PAT" -X DELETE "https://$INSTANCE_URL/repos/$CLASS_ORG/conflict-practice-$USER_NAME" >>log.out 2>&1
        CreateRepo "$USER_NAME"
      else
        echo "A new conflict-practice repo wasn't created for $USER_NAME..."
      fi
    fi
  done
  popd || return

  # Remove the local file
  echo "Remove the local (temporary) clone"
  rm -rf conflict-template
}

function CreateRepo() {
  STUDENT=$1
  STUDENT_REPO="conflict-practice-$STUDENT"
  echo "Time to create $STUDENT_REPO for $STUDENT"

  # Create a repo named conflict-practice-$STUDENT in $CLASS_ORG org
  echo "Create server-side location for fresh $CLASS_ORG/$STUDENT_REPO repo..."
  curl -s -i -u "$TOKEN_OWNER:$TEACHER_PAT" -d "{ \"name\": \"$STUDENT_REPO\", \"description\": \"Let's resolve some conflicts.\", \"private\": false, \"has_issues\": true, \"has_wiki\": true, \"has_downloads\": true}" -X POST "https://$INSTANCE_URL/orgs/$CLASS_ORG/repos" >>log.out 2>&1

  # Wait to let finish
  echo "Resting 5 seconds to allow repo creation to resolve"
  sleep 5

  # Add STUDENT as a collaborator
  curl -s -i -u "$TOKEN_OWNER:$TEACHER_PAT" -X PUT "https://$INSTANCE_URL/repos/$CLASS_ORG/$STUDENT_REPO/collaborators/$STUDENT" >>log.out 2>&1
  echo "Push the fresh $STUDENT_REPO back to $CLASS_ORG ..."
  git push --mirror "https://$TOKEN_OWNER:$TEACHER_PAT@$ROOT_URL/$CLASS_ORG/$STUDENT_REPO" >>log.out 2>&1

  # Wait to let finish
  echo "Waiting for push to resolve before creating pull requests."
  sleep 5

  # Set default branch to main
  curl -s -i -u "$TOKEN_OWNER:$TEACHER_PAT" -d "{\"default_branch\":\"main\"}" -X PATCH "https://$INSTANCE_URL/repos/$CLASS_ORG/$STUDENT_REPO" >>log.out 2>&1

  # Create PRs for each branch
  {
    curl -s -i -u "$TOKEN_OWNER:$TEACHER_PAT" -d "{ \"title\": \"Updates to game manual\", \"head\": \"manual\", \"base\": \"main\", \"body\": \"This pull request edits the wording of some of the language on the main page. It appears that it has also been edited on main, because there's a merge conflict. Please make sure that all of the words are the ones that you'd like to use, and that there aren't any lines of text missing.\n\nIf you need any help resolving this conflict, check out this video: https://vimeo.com/225093022/6c1c6eb72b\"}" -X POST "https://$INSTANCE_URL/repos/$CLASS_ORG/$STUDENT_REPO/pulls"
    curl -s -i -u "$TOKEN_OWNER:$TEACHER_PAT" -d "{ \"title\": \"Minor CSS fixes\", \"head\": \"css-changes\", \"base\": \"main\", \"body\": \"This pull request makes some small changes to the CSS. Pick the CSS that you think makes the most sense given the history of the file on both branches and resolve the merge conflict.\n\nIf you need any help resolving this conflict, check out this video: https://vimeo.com/225086721/5a00221234\"}" -X POST "https://$INSTANCE_URL/repos/$CLASS_ORG/$STUDENT_REPO/pulls"
    curl -s -i -u "$TOKEN_OWNER:$TEACHER_PAT" -d "{ \"title\": \"Update README\", \"head\": \"readme-update\", \"base\": \"main\", \"body\": \"This pull request updates the README.md. Resolve the merge conflicts and make sure the final version of the README.md is accurate and descriptive.\n\nIf you need any help resolving this conflict, check out this video: https://vimeo.com/225086807/17d3c84475\"}" -X POST "https://$INSTANCE_URL/repos/$CLASS_ORG/$STUDENT_REPO/pulls"
  } >>log.out 2>&1

  # Assign PRs to $STUDENT
  for OWNER in {1..3}; do
    curl -s -i -u "$TOKEN_OWNER:$TEACHER_PAT" -d "{\"assignees\": [\"$STUDENT\"]}" -X POST "https://$INSTANCE_URL/repos/$CLASS_ORG/$STUDENT_REPO/issues/$OWNER/assignees" >>log.out 2>&1
  done
}

# Get User names
GetNames
