#!/bin/bash

# script/server: produce jekyll site of the manual

set -e

cd "$(dirname "$0")/.."

remote=$(git config remote.origin.url)
git config --global user.email "$GH_EMAIL" > /dev/null 2>&1
git config --global user.name "$GH_NAME" > /dev/null 2>&1
#git init
#git remote add --fetch origin "$remote"

rm -rf vendor
rm .ruby-version

mv mybook.pdf training-manual-temp.pdf

git checkout gh-pages --force
git pull origin gh-pages --rebase
cp -R _book/* .
git clean -fx node_modules
git clean -fx _book

git status

rm -rf training-manual.pdf
mv training-manual-temp.pdf training-manual.pdf

git add .
git commit -m "update book [ci skip]"

#bundle install

echo -e "\n\n"
echo "==> Deploying..."
echo -e "\n\n"

git push
