#!/bin/bash

# Useage: script/create-manual <class>
# Generate the student or teacher manual for a given class

set -e

cd "$(dirname "$0")/.."

if [[ ! $1 = *.md ]] || [ ! -f $1 ]; then
  echo "bad argument!" >&2
  exit 1;
fi
student="${1%.md}-student-manual"
facilitator="${1%.md}-facilitator-manual"

echo "==> Generating student and facilitator manuals from $1"
bundle exec script/render.rb -s "$1" > "${student}".md
bundle exec script/render.rb -f "$1" > "${facilitator}".md
pandoc -f markdown_github -t html5 -o "${student}".html "${student}".md
pandoc -f markdown_github -t html5 -o "${student}".html "${facilitator}".md
pdfify "${student}".md
pdfify "${facilitator}".md
