#!/bin/bash

# script/create-manual: generate the student or teacher manual for a given class

set -e

cd "$(dirname "$0")/.."

script/bootstrap

if [[ ! $1 = *.adoc ]] || [ ! -f $1 ]; then
  echo "bad argument!" >&2
  exit 1;
fi
output_file="${1%.adoc}"
common_args="-a pdf-stylesdir=theme -a pdf-style=manual -a pdf-fontsdir=fonts"

echo "==> Generating student and facilitator manuals from $1"
eval asciidoctor-pdf "$common_args -o $output_file-student-manual.pdf $1"
eval asciidoctor-pdf "$common_args -a fac-notes -o $output_file-facilitator-manual.pdf $1"
