#!/usr/bin/env bash
#
# Remove Repo

#################################################################
# NOTE: You must have a personal access token (PAT)             #
# saved to your environment variables to use this script.       #
# We recommend a dedicated service account (e.g. githubteacher) #
#################################################################

# GLOBALS
REPO_NAME=$1

function DeleteIt() {
  echo "Deleting $CLASS_ORG/$REPO_NAME"
  curl -s -i -H "Authorization: token $TEACHER_PAT" -X DELETE "https://$INSTANCE_URL/repos/$CLASS_ORG/$REPO_NAME" >>log.out 2>&1

  # Load the error code
  ERROR_CODE=$?

  # Check the shell for errors
  if [ $ERROR_CODE -ne 0 ]; then
    echo "ERROR! Failed to Delete it!"
    exit 1
  fi
}

# Delete the repo
DeleteIt
