#!/bin/sh

#you must have a githubteacher token
#saved to your ENV variables in order to use this script
reponame=$1

set -x

function deleteit () {
  curl -i -H "Authorization: token $TEACHER_PAT" -X DELETE https://$INSTANCE_URL/repos/$CLASS_ORG/$reponame
}

deleteit
