#!/bin/sh

#you must have a githubteacher token
#saved to your ENV variables in order to use this script
#your token must have DELETE permissions

function resetactivity () {
  reponame=$1
  default_branch=$2

  #make sure no one is teaching class
  echo "Is anyone teaching a class right now using $TOKEN_OWNER? (Y or N)"
  read classtime
  if echo "$classtime" | grep -iq "^y" ;
  then
    echo "This is not a good time to run this script. Wait until class is over and try again"
    exit
  else
    deletedisposablerepo $reponame

    echo "Resting 5 seconds to all deletions to resolve"
    sleep 5

    echo "Creating a fresh repo for $CLASS_ORG"
    duplicaterepo $reponame $default_branch
  fi
}

function deletedisposablerepo () {
  reponame=$1

  echo "Delete $TOKEN_OWNER $reponame repo..."
  curl -s -i -u "$TOKEN_OWNER:$TEACHER_PAT" -X DELETE https://$INSTANCE_URL/repos/$TOKEN_OWNER/$1 >> log.out 2>&1

  echo "Delete $CLASS_ORG $reponame repo..."
    curl -s -i -u "$TOKEN_OWNER:$TEACHER_PAT" -X DELETE https://$INSTANCE_URL/repos/$CLASS_ORG/$1 >> log.out 2>&1
}

function duplicaterepo () {
  reponame=$1
  dbranch=$2

  echo "Create server-side location for fresh $CLASS_ORG/$reponame repo..."
  curl -s -i -u "$TOKEN_OWNER:$TEACHER_PAT" -d "{ \"name\": \"$reponame\", \"description\": \"A fun way to learn about Git and GitHub\", \"homepage\": \"https://$CLASS_ORG.github.io/github-games\", \"private\": false, \"has_issues\": true, \"has_wiki\": true, \"has_downloads\": true}" -X POST https://$INSTANCE_URL/orgs/$CLASS_ORG/repos >> log.out 2>&1

  echo "Resting 5 more seconds to allow repo creation to resolve"
  sleep 5

  echo "Clone $reponame template from githubtraining org..."
  rm -rf $reponame

  echo "Trying to clone a template repo from github.com. If you're behind a firewall, this command may time out and we'll try to clone from your instance, instead."
  echo "The timeout may take some time..."

  git clone --bare https://github.com/githubtraining/$reponame $reponame >> log.out 2>&1
  if [ $? -ne 0 ]; then
    echo "!!! Wasn't able to clone the template repo from github.com. Trying to clone from your own instance."
    git clone --bare https://$TOKEN_OWNER:$TEACHER_PAT@$ROOT_URL/$CLASS_ORG/$reponame $reponame >> log.out 2>&1
    if [ $? -ne 0 ]; then
      echo "!!! Couldn't clone template repo at all. Please grab a copy from https://github.com/githubtraining/$reponame and upload it to your GHE instance."
      exit 1
    fi
  fi

  # git clone --bare https://github.com/githubtraining/$reponame $reponame
  # if [ $? -eq 0 ]; then
  echo "Push the fresh $reponame back to $CLASS_ORG's repo..."
  pushd $reponame
  git push --mirror https://$TOKEN_OWNER:$TEACHER_PAT@$ROOT_URL/$CLASS_ORG/$reponame >> log.out 2>&1

  echo "Resting 5 more seconds to allow push to resolve"
  sleep 5

  echo "Setting default branch for repo"
  curl -s -i -u "$TOKEN_OWNER:$TEACHER_PAT" -d "{\"name\": \"$reponame\", \"default_branch\": \"$dbranch\"}" https://$INSTANCE_URL/repos/$CLASS_ORG/$reponame >> log.out 2>&1
  popd

  echo "Remove the local (temporary) clone"
  rm -rf $reponame
}

#usage list the repository name and default branch
resetactivity github-games master
