[[_setup_git]]
=== Setting Up Git

Git is the open source application that GitHub uses to version control your content. You will need Git installed in order to work with your files locally on the Command Line.

You may already have Git installed so let's check! Open Terminal if you are on a Mac, or Powershell if you are on a Windows machine, and type:

[source,console]
----
$ git --version
----

You should get something like this:

[source,console]
----
$ git --version
git version 2.6.3
----

Anything over 1.9.5 will work for this class!

==== Installing Git

If you don't already have Git installed, you have two options:

1. Download and install Git at www.git-scm.com.
2. Install it as part of the GitHub Desktop package found at desktop.github.com.

If you need additional assistance installing Git, you can find more information in this ProGit chapter on http://git-scm.com/book/en/v2/Getting-Started-Installing-Git[installing Git].

==== Finding Your Shell

If you just installed Git on your Windows machine, now is a good time to create a shortcut to the command line application you will want to use with Git. You can use `PowerShell` or `Git Bash` which is installed with the Git package.

Once you find it, go ahead and open it!
