[[_setup_git]]
=== Step 2: Install Git

Git is the open source application GitHub uses to version control your content. You will need Git installed in order to work with your files locally.

You may already have Git installed so let's check! Open Terminal if you are on a Mac, or Powershell if you are on a Windows machine, and type:

[source,console]
----
$ git --version
----

You should see something like this:

[source,console]
----
$ git --version
git version 2.6.3
----

Anything over 1.9.5 will work for this class!

==== Downloading and Installing Git

If you don't already have Git installed, you have two options:

1. Download and install Git at www.git-scm.com.
2. Install it as part of the GitHub Desktop package found at desktop.github.com.

If you need additional assistance installing Git, you can find more information in this ProGit chapter on http://git-scm.com/book/en/v2/Getting-Started-Installing-Git[installing Git].

==== Where is Your Shell?

Now is a good time to create a shortcut to the command line application you will want to use with Git:

* If you are working on Windows, you can use `PowerShell` or `Git Bash` which is installed with the Git package.
* If you are working on a Mac or other Unix based system, you can use the terminal application.

Go ahead and open your command line application now!
