[[_introduce_git]]
=== What is Git?

Git is a *distributed* version control system. As we begin to discuss Git (and what makes it special) it would be helpful if you could forget everything you know about version control systems for just a moment. Git stores and thinks about information very differently than other version control systems.

We will explore how Git thinks about information as we go through this class, but the first thing you will need to understand is how Git versions your content.

==== Snapshots, not Deltas

One of the first ideas you will need understand is that Git does not store your version information as changes. Instead Git takes a snapshot of your repository at a given point in time.

==== Optimized for Local Operations

Git is optimized for local operation. When you clone a copy of a repository to your local machine, you receive a copy of the entire repository and its history. This means you can work on the plane, on the train, or anywhere else your adventures find you!

==== Branches are Lightweight and Cheap

Branches are one of the concepts that are most difficult to understand in Git.

When you create a new branch in Git, you are actually just creating a pointer that corresponds to the most recent snapshot in a line of work. Git keeps the snapshots for each branch separate until you explicitly tell it to merge those snapshots in with the main line of work.

==== Git is Explicit

Which brings us to our final point for now, which is Git is a very explicit application. It does not do anything with your data until you tell it to. No auto-saves or auto-syncing with the remote, Git waits for you to tell it when to take a snapshot and when to send that snapshot to the remote.  
