### Activity: Creating A Branch with GitHub

Earlier you created an issue to add a file about your home town. Let's create a branch that you will use to add your file.

Follow these steps to create a new branch in the class repository:

.Activity Instructions
[cols="1,4",options="header"]
|================================
| Step    | Description
| 1       | Navigate to the `class repository`
| 2       | Click the branch dropdown
| 3       | Enter the branch name 'firstname-lastname-hometown'
| 4       | Press `Enter`
|================================


When you create a new branch on GitHub, you are automatically switched to your branch. Now, any changes you make to the files in the repository will be applied to this new branch.

[NOTE]
====
Creating branch on GitHub before cloning is a good practice to reduce conflicts.
====

[WARNING]
====
A word of caution. When you leave the repository and come back, notice that GitHub automatically assumes you want to see the items on the master branch. If you want to continue working on your branch, you will need to reselect it using the branch dropdown.
====
