[[_pull_request]]
=== Creating a Pull Request

Pull Requests are used to propose changes to the project files. A pull request introduces an action that addresses an Issue. A Pull Request is considered a "work in progress" until it is merged into the project. Now that you have created a file, you will open a pull request to discuss the file with your team mates.

Use the following instructions to create your first Pull Request:

.Activity Instructions
[cols="1,4",options="header"]
|================================
| Step    | Description
| 1       | Click the Pull Request icon.
| 2       | Click New Pull Request.
| 3       | In the *base* dropdown, choose `master`
| 4       | In the *compare* dropdown, choose your branch.
| 5       | Type a subject line and enter a comment.
| 6       | Click Create Pull Request.
|================================

[NOTE]
====
When you navigate to the class repository, you should see a banner at the top of the page indicating you have recently pushed branches, along with a button that reads *Compare & pull request*. This helpful button will automatically start the pull request process between your branch and the repository's default branch.
====
