[[_pull_request]]
### Activity: Creating a Pull Request

Pull Requests are used to propose changes to the project files. A pull request introduces an action that addresses an Issue. A Pull Request is considered a "work in progress" until it is merged into the project. Now that you have created a file, you will open a pull request to discuss the file with your team mates.

Follow these steps to create a Pull Request in the class repository:

.Activity Instructions
. Click the Pull Request icon.
. Click New Pull Request.
. In the *base* dropdown, choose `master`
. In the *compare* dropdown, choose your branch.
. Type a subject line and enter a comment.
. Use markdown formatting to add a header and a checklist to your Pull Request.
. @mention the teacher.
. Use one of the keywords `closes`, `fixes`, or `resolves` to note which Issue the Pull Request resolves.
. Use `Preview` to see how your Pull Request will look.
. Assign the Pull Request to yourself.
. Click Create Pull Request.
. Comment on another class member's Pull Request requesting additional information.


[NOTE]
====
When you navigate to the class repository, you should see a banner at the top of the page indicating you have recently pushed branches, along with a button that reads *Compare & pull request*. This helpful button will automatically start the pull request process between your branch and the repository's default branch.
====
