[[_delete_branches]]
### Cleaning Up Your Branches

When you merged your Pull Request, you deleted the branch on GitHub, but this will not automatically delete your local copy of the branch. Let's go back to our Terminal and do some cleanup.

[source,console]
----
$ git checkout master
$ git pull # <1>
$ git branch --all # <2>
----
<1> retrieves all of the changes from GitHub and brings them down to your local machine.
<2> shows you all of the branches that exist locally, both ones you can work with and the read-only copies of the remote tracking branches.

You will probably see that your branch is still there, both as a local branch and as a read-only remote tracking branch.

[source,console]
----
$ git branch --merged
----

Adding the `--merged` option to the `git branch` command allows you to see which branches have history equivalent to the history on the checked out branch. In this case, since we are checked out to master, we will use this command to ensure all of the changes on our feature branch have been merged to master before we delete the branch.

To delete the local branch, type the following command:

[source,console]
----
$ git branch -d <branch-name>
----

If you type `git branch --all` again, you will see that your local branch is gone but the remote tracking branch is still there. To delete the remote tracking branch, type:

[source,console]
----
$ git pull --prune
----

[NOTE]
====
If you would like pruning of the remote tracking branches to be set as your default behavior when you pull, you can use the following configuration option: `git config --global fetch.prune true`.
====
