[[_multiple_remotes]]
## Working with Multiple Remotes

When we created our fork, we discussed the fact that a fork is a static copy of the repository at the point in time when we clicked the fork button.

In the real world, changes will continue to happen on the original project as new features are added and bugs are fixed. How can we pull these changes made to the original repository into our copy? Let's find out.

.Activity Instructions
. Type `git remote add upstream https://github.com/githubschool/github-games.git` to create a new remote
. Type `git remote -v` to confirm your remote settings.
. Type `git fetch upstream` to pull down the remote tracking branches from upstream.
. Type `git checkout -b shape-colors origin/shape-colors` to create a branch called shape-colors based on the one in your fork of the repository.
. Type `git diff shape-colors upstream/shape-colors` to see the difference between your branch and the upstream branch.
. Type `git merge upstream/shape-colors` to merge in the changes.
. Type `git push` to send shape-colors to the remote.
. Create a Pull Request in your repository.

[NOTE]
====
If you would like to keep things tidy, you can use `git remote remote upstream` once you have completed the merge. This will remove the remote and the remote tracking branches associated with it.
====
