[[_reset_mixed]]
### Reset Mixed

After the soft reset, your file directory should still look like this:

To prepare for this activity, you will need to create four files and commit each separately so your file directory looks like this:

[source,console]
----
$ ls
file1.md
file2.md
file3.md
file4.md
README.md
----

But your history should now look like this:

[source,console]
----
$ git log --oneline
78fjuoz grouping commits for cleaner history
39dj58s init file 2
dke03md init file 1
84nqdkq initializing repo with README
----

Next we will try the mixed reset:

. Once again, we will start by viewing the history of our project.
. This time we only want to go back one commit in history so we will type `git reset HEAD~` OR `git reset <SHA>`.
. Type `git status`. The changes we made in the last commit have been moved back to the working directory.
. This time, we will need to `git add` the files to the staging area before we can commit them.
. Go ahead and re-commit the files with `git commit -m "another reset example"`.

[NOTE]
====
Remember, mixed is the default mode for the reset command.
====
